### ISSUE TITLE
Password protected links?

### ISSUE THREAD

**Issue by sintaxx** [Quatrecentquatre-404/gofile-downloader#1]
I can't seem to get this to work with password protected gofile galleries, is there a way to make this work ?

**Comment by Quatrecentquatre-404** [comment]
Hi, thanks for the issue.
Can you send me the link of this resource with it's password to let me figure it out ? I never faced this kind of resource yet.

**Comment by bnsave100** [comment]
> Hi, thanks for the issue. Can you send me the link of this resource with it's password to let me figure it out ? I never faced this kind of resource yet.
> 
> _If you want to keep it private, you can join me on Discord : `Quatrecentquatre#0404`, or through a mail : [obvious.ly.dev@gmail.com](mailto:obvious.ly.dev@gmail.com) ._

https://gofile.io/d/UHnWoY pass:`abcd1234`

**Comment by Quatrecentquatre-404** [comment]
> > Hi, thanks for the issue. Can you send me the link of this resource with it's password to let me figure it out ? I never faced this kind of resource yet.
> > _If you want to keep it private, you can join me on Discord : `Quatrecentquatre#0404`, or through a mail : [obvious.ly.dev@gmail.com](mailto:obvious.ly.dev@gmail.com) ._
> 
> https://gofile.io/d/UHnWoY pass:`abcd1234`

Thanks for the answer, I pushed  patch to handle passwords folders. You can find an example in the ``config.json`` file.
